CREATE TABLE "User"
(
    "id"    integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome"  varchar NOT NULL,
    "email" varchar NOT NULL,
    "país"  varchar NOT NULL,
    "cep"   varchar NOT NULL,
    "senha" varchar(255)
);

CREATE TABLE "Competencias"
(
    "id"          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "competencia" varchar NOT NULL
);

CREATE TABLE "VagaCompetencia"
(
    "id_vaga"        integer NOT NULL,
    "id_competencia" integer NOT NULL
);

CREATE TABLE "CandidatoCompetencia"
(
    "id_candidato"   integer NOT NULL,
    "id_competencia" integer NOT NULL
);

CREATE TABLE "Candidate"
(
    "id_candidato"    integer PRIMARY KEY NOT NULL,
    "cpf"             varchar UNIQUE      NOT NULL,
    "sobrenome"       varchar             NOT NULL,
    "data_nascimento" date                NOT NULL,
    "descricao"       varchar             NOT NULL,
    "formacao"        varchar
);

CREATE TABLE "Company"
(
    "id_empresa" integer PRIMARY KEY NOT NULL,
    "cnpj"       varchar UNIQUE      NOT NULL
);

CREATE TABLE "Vaga"
(
    "id"              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_empresa"      integer NOT NULL,
    "titulo"          varchar NOT NULL,
    "descricao"       varchar NOT NULL,
    "local_vaga"      varchar NOT NULL,
    "id_competencias" integer NOT NULL
);

CREATE TABLE "Curtida"
(
    "id_candidato"      integer,
    "id_vaga"           integer,
    "curtida_candidato" boolean NOT NULL DEFAULT false,
    "curtida_empresa"   boolean NOT NULL DEFAULT false,
    "data_match"        timestamp,
    PRIMARY KEY ("id_candidato", "id_vaga")
);

COMMENT ON COLUMN "User"."senha" IS 'Mínimo de 6 caracteres. Armazenar apenas o hash criptografado.';

ALTER TABLE "VagaCompetencia"
    ADD FOREIGN KEY ("id_vaga") REFERENCES "Vaga" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "VagaCompetencia"
    ADD FOREIGN KEY ("id_competencia") REFERENCES "Competencias" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CandidatoCompetencia"
    ADD FOREIGN KEY ("id_candidato") REFERENCES "Candidate" ("id_candidato") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "CandidatoCompetencia"
    ADD FOREIGN KEY ("id_competencia") REFERENCES "Competencias" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Candidate"
    ADD FOREIGN KEY ("id_candidato") REFERENCES "User" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Company"
    ADD FOREIGN KEY ("id_empresa") REFERENCES "User" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Vaga"
    ADD FOREIGN KEY ("id_empresa") REFERENCES "Company" ("id_empresa") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Vaga"
    ADD FOREIGN KEY ("id_competencias") REFERENCES "Competencias" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Curtida"
    ADD FOREIGN KEY ("id_candidato") REFERENCES "Candidate" ("id_candidato") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Curtida"
    ADD FOREIGN KEY ("id_vaga") REFERENCES "Vaga" ("id") DEFERRABLE INITIALLY IMMEDIATE;
